name: PyPI-Release

on:
  push:
    branches:
      - test-github-actions

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.x"
      - name: Install cloudevents and GitPython
        run: pip install -U cloudevents 'GitPython==3.1.7'
      - name: Create Tag
        run: python pypi_packaging.py